version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    container_name: frontend-dev
    restart: always
    networks:
      - traefik_proxy
    labels:
          - traefik.http.services.frontend.loadbalancer.server.port=8081
          - traefik.http.routers.frontend.rule=Host(`transfer-flow.studio`)
          - traefik.http.routers.frontend.tls.certresolver=myresolver
networks:
    traefik_proxy:
      name: traefik_proxy
      external: true
