version: '3.1'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    container_name: frontend-dev
    ports:
      - "8081:80"
    restart: always
