name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests and collect coverage
        run: cd ${{ github.workspace }} && npm test -- --coverage

      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.testExecutionReportPaths=/home/runner/work/t-flow/coverage/test-report.xml
            -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
